/**
 * ============================================================
 * MASTER COMPUTER ACADEMY — CENTRALIZED BUSINESS CONFIGURATION
 * ============================================================
 * Update this single file to reflect verified business information.
 * All components read from here — no need to search across files.
 *
 * Fields marked [UPDATE] require real information from the academy owner.
 * ============================================================
 */

// ── Contact ────────────────────────────────────────────────
export const PHONE_NUMBER      = '9156348591';
export const WHATSAPP_NUMBER   = '919156348591';     // International format, no +
export const EMAIL             = '[UPDATE: academy@email.com]';    // [UPDATE] Email address (optional)

// ── WhatsApp message templates ─────────────────────────────
export const WA_MSG_GENERAL    = encodeURIComponent('नमस्कार Master Computer Academy, मला MS-CIT कोर्सबद्दल माहिती हवी आहे.');
export const WA_MSG_ADMISSION  = encodeURIComponent('नमस्कार Master Computer Academy, मला MS-CIT कोर्सबद्दल माहिती हवी आहे.');
export const WA_MSG_EN         = encodeURIComponent('Hello Master Computer Academy, I am interested in the MS-CIT course. Please share the course and batch details.');

export function waCourseMsg(courseName) {
  return encodeURIComponent(
    `नमस्कार Master Computer Academy, मला ${courseName} Course बद्दल माहिती हवी आहे. कृपया fees आणि batch details सांगाल का?`
  );
}

export function waLink(msg = WA_MSG_GENERAL) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`;
}

export function callLink() {
  return `tel:${PHONE_NUMBER}`;
}

// ── Academy info ───────────────────────────────────────────
export const ACADEMY_NAME      = 'Master Computer Academy';
export const ACADEMY_SHORT     = 'Master Computers';
export const TAGLINE_MARATHI   = 'MS-CIT शिका, Digital Skills वाढवा!';
export const TAGLINE_ENGLISH   = 'Computer Education Made Simple';
export const TAGLINE_SUB       = 'तुमच्या Digital भविष्यासाठी संगणक शिक्षणाची योग्य सुरुवात Master Computer Academy सोबत.';

// ── Address ────────────────────────────────────────────────
export const ADDRESS_LINE1     = 'Lok Kalyan Society, Anmol Nagar';
export const ADDRESS_LINE2     = 'Wathoda Layout, Nagpur';
export const ADDRESS_STATE     = 'Maharashtra';
export const ADDRESS_PINCODE   = '440034';
export const ADDRESS_FULL      = `${ADDRESS_LINE1}, ${ADDRESS_LINE2}, ${ADDRESS_STATE} – ${ADDRESS_PINCODE}`;
export const GOOGLE_MAPS_URL   = 'https://maps.google.com/?q=Master+Computer+Academy+Wathoda+Layout+Nagpur+440034'; // [UPDATE with exact verified Maps link]
export const GOOGLE_MAPS_EMBED = '';                               // [UPDATE: paste Google Maps embed src URL]

// ── Business hours ─────────────────────────────────────────
export const HOURS = [
  { days: 'सोमवार – शनिवार', time: 'सकाळी ८:०० – रात्री ९:००' },  // Monday–Saturday 8:00 AM – 9:00 PM
  { days: 'रविवार',           time: 'Not provided' },
];

// ── Social media ───────────────────────────────────────────
export const SOCIAL = {
  facebook:  '',   // [UPDATE]
  instagram: '',   // [UPDATE]
  youtube:   '',   // [UPDATE]
  google:    'https://www.justdial.com/Nagpur/Master-Computer-Academy-Near-Wathoda-Police-Station-Wathoda-Layout/0712PX712-X712-160812003119-P6B3_BZDET',
};

// ── Course Categories ───────────────────────────────────────
export const COURSE_CATEGORIES = [
  { id: 'mscit',      label: 'MS-CIT & Career Programs', icon: '⭐', labelMarathi: 'MS-CIT आणि Career Programs' },
  { id: 'accounting', label: 'Accounting & Office',       icon: '💼', labelMarathi: 'Accounting आणि Office' },
  { id: 'design',     label: 'Design & Creative',         icon: '🎨', labelMarathi: 'Design आणि Creative' },
  { id: 'computer',   label: 'Computer & Technology',     icon: '💻', labelMarathi: 'Computer आणि Technology' },
  { id: 'typing',     label: 'Typing Courses',            icon: '⌨️', labelMarathi: 'Typing Courses' },
];

// ── Courses — 25 VERIFIED courses ──────────────────────────
// Fees and batch timings not yet provided — do NOT add until verified.
export const COURSES = [

  // ── MS-CIT & Career Combo Programs ───────────────────────
  {
    id: 'mscit',
    category: 'mscit',
    icon: '🎓',
    name: 'MS-CIT',
    nameMarathi: 'एम-एस-सीआयटी',
    badge: 'Featured',
    isCombo: false,
    isMscit: true,
    duration: null,           // [UPDATE: duration to be provided]
    fees: null,               // [UPDATE: fees to be provided]
    shortDesc: 'Maharashtra State Certificate in Information Technology — संगणकाचे मूलभूत ज्ञान मिळवा.',
    longDesc: 'MS-CIT हा महाराष्ट्रातील अत्यंत लोकप्रिय Computer Literacy course आहे. हा course विद्यार्थी, नोकरी शोधणारे आणि गृहिणींसाठी उपयुक्त आहे.',
  },
  {
    id: 'mscit-combo-1',
    category: 'mscit',
    icon: '🏆',
    name: 'MS-CIT + ENG30 + ENG40 + Diploma',
    nameMarathi: 'MS-CIT + English Typing + Diploma',
    badge: 'Career Program',
    isCombo: true,
    isMscit: false,
    duration: '6 Months',
    fees: null,               // [UPDATE]
    certificates: 4,
    shortDesc: 'एकाच program मध्ये MS-CIT, English Typing (30 & 40 WPM) आणि Diploma — 4 Certificates मिळवा.',
    longDesc: 'MS-CIT + English Typing 30 WPM + English Typing 40 WPM + Diploma — एकाच 6-month learning journey मध्ये.',
  },
  {
    id: 'mscit-combo-2',
    category: 'mscit',
    icon: '🏆',
    name: 'MS-CIT + ENG30 + ENG40 + Tally Prime + Diploma',
    nameMarathi: 'MS-CIT + Typing + Tally + Diploma',
    badge: 'Career Program',
    isCombo: true,
    isMscit: false,
    duration: '8 Months',
    fees: null,               // [UPDATE]
    certificates: 4,
    shortDesc: 'MS-CIT, English Typing, Tally Prime आणि Diploma — सर्व एकत्र! 4 Certificates आणि comprehensive skills.',
    longDesc: 'MS-CIT + English Typing 30 WPM + English Typing 40 WPM + Tally Prime with GST + Diploma — 8-month comprehensive career program.',
  },
  {
    id: 'mscit-eng30',
    category: 'mscit',
    icon: '🎓',
    name: 'MS-CIT + ENG30',
    nameMarathi: 'MS-CIT + English Typing',
    badge: '',
    isCombo: true,
    isMscit: false,
    duration: '3 Months',
    fees: null,               // [UPDATE]
    certificates: null,
    shortDesc: 'MS-CIT सोबत English Typing 30 WPM — 3 months मध्ये दोन skills एकत्र शिका.',
    longDesc: 'MS-CIT आणि English Typing 30 WPM combo program — 3 months.',
  },

  // ── Accounting & Office ───────────────────────────────────
  {
    id: 'advanced-excel',
    category: 'accounting',
    icon: '📊',
    name: 'Advanced Excel',
    nameMarathi: 'अडवान्स्ड Excel',
    badge: '',
    isCombo: false,
    duration: '2 Months',
    fees: null,
    shortDesc: 'Excel मध्ये practical skills विकसित करा — formulas, charts, data analysis.',
  },
  {
    id: 'tally-prime-gst',
    category: 'accounting',
    icon: '💼',
    name: 'Tally Prime with GST',
    nameMarathi: 'Tally Prime with GST',
    badge: '',
    isCombo: false,
    duration: '2 Months',
    fees: null,
    shortDesc: 'Tally Prime आणि GST billing शिका — accountants आणि business owners साठी.',
  },
  {
    id: 'advanced-tally-prime-gst',
    category: 'accounting',
    icon: '💼',
    name: 'Advanced Tally Prime with GST',
    nameMarathi: 'अडवान्स्ड Tally Prime with GST',
    badge: '',
    isCombo: false,
    duration: '2 Months',
    fees: null,
    shortDesc: 'Tally Prime चे advanced features आणि GST accounting सखोलपणे शिका.',
  },
  {
    id: 'office-assistance',
    category: 'accounting',
    icon: '📄',
    name: 'Office Assistance',
    nameMarathi: 'Office Assistance',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Office साठी आवश्यक computer skills — MS Office, email, documentation.',
  },
  {
    id: 'account-expert-tally',
    category: 'accounting',
    icon: '🧾',
    name: 'Certificate in Account Expert with Tally.ERP9',
    nameMarathi: 'Account Expert with Tally.ERP9',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Tally.ERP9 सोबत accounting expertise — commerce students आणि accountants साठी.',
  },
  {
    id: 'tally-erp9-advanced',
    category: 'accounting',
    icon: '🧾',
    name: 'Certificate in Tally.ERP9 Advanced (GST) + Prime',
    nameMarathi: 'Tally.ERP9 Advanced (GST) + Prime',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Tally.ERP9 Advanced GST आणि Tally Prime — comprehensive accounting course.',
  },

  // ── Design & Creative ─────────────────────────────────────
  {
    id: 'graphic-designing',
    category: 'design',
    icon: '🎨',
    name: 'Graphic Designing',
    nameMarathi: 'Graphic Designing',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Professional graphic design skills — posters, logos, social media creatives.',
  },
  {
    id: 'klic-video-editing',
    category: 'design',
    icon: '🎬',
    name: 'KLiC Video Editing',
    nameMarathi: 'KLiC Video Editing',
    badge: '',
    isCombo: false,
    duration: '2 Months',
    fees: null,
    shortDesc: 'Video editing skills — reels, YouTube videos आणि professional content तयार करा.',
  },
  {
    id: 'klic-web-designing',
    category: 'design',
    icon: '🌐',
    name: 'KLiC Web Designing',
    nameMarathi: 'KLiC Web Designing',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Professional websites design करायला शिका — HTML, CSS आणि web tools.',
  },
  {
    id: 'cert-dtp',
    category: 'design',
    icon: '🖨️',
    name: 'Certificate in Desktop Publishing',
    nameMarathi: 'Desktop Publishing Certificate',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Desktop publishing skills — print design, layout आणि publishing software.',
  },
  {
    id: 'diploma-dtp',
    category: 'design',
    icon: '🖨️',
    name: 'Diploma in Desktop Publishing',
    nameMarathi: 'Desktop Publishing Diploma',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Diploma level desktop publishing — advanced print design आणि layout skills.',
  },
  {
    id: 'cert-web-design',
    category: 'design',
    icon: '🌐',
    name: 'Certificate in Web Design',
    nameMarathi: 'Web Design Certificate',
    badge: '',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Web design certificate course — professional websites बनवायला शिका.',
  },

  // ── Computer & Technology ─────────────────────────────────
  {
    id: 'google-workspace',
    category: 'computer',
    icon: '☁️',
    name: 'Google Workspace Expert',
    nameMarathi: 'Google Workspace Expert',
    badge: '',
    isCombo: false,
    duration: '2 Months',
    fees: null,
    shortDesc: 'Gmail, Google Docs, Sheets, Drive — Google Workspace tools expert बना.',
  },
  {
    id: 'hardware-networking',
    category: 'computer',
    icon: '🔧',
    name: 'Certificate in Hardware and Networking',
    nameMarathi: 'Hardware आणि Networking',
    badge: '',
    isCombo: false,
    duration: '5 Months',
    fees: null,
    shortDesc: 'Computer hardware, assembly, troubleshooting आणि networking basics शिका.',
  },
  {
    id: 'ccc',
    category: 'computer',
    icon: '🏛️',
    name: 'Course on Computer Concepts (CCC)',
    nameMarathi: 'CCC — Government of India',
    badge: 'Govt. of India',
    isCombo: false,
    duration: '3 Months',
    fees: null,
    shortDesc: 'Government of India — NIELIT द्वारे Computer Concepts course. सरकारी jobs साठी उपयुक्त.',
  },

  // ── Typing Courses ────────────────────────────────────────
  {
    id: 'eng-typing-30',
    category: 'typing',
    icon: '⌨️',
    name: 'Certificate in Computer Based English Typing - 30 W.P.M.',
    nameMarathi: 'English Typing — 30 W.P.M.',
    badge: '',
    isCombo: false,
    isTyping: true,
    typingLang: 'English',
    typingSpeed: '30 W.P.M.',
    duration: '3 Months',
    fees: null,
    shortDesc: 'English Typing 30 Words Per Minute — typing certificate साठी ideal.',
  },
  {
    id: 'eng-typing-40',
    category: 'typing',
    icon: '⌨️',
    name: 'Certificate in Computer Based English Typing - 40 W.P.M.',
    nameMarathi: 'English Typing — 40 W.P.M.',
    badge: '',
    isCombo: false,
    isTyping: true,
    typingLang: 'English',
    typingSpeed: '40 W.P.M.',
    duration: '3 Months',
    fees: null,
    shortDesc: 'English Typing 40 Words Per Minute — faster speed certificate.',
  },
  {
    id: 'marathi-typing-30',
    category: 'typing',
    icon: '⌨️',
    name: 'Certificate in Computer Based Marathi Typing - 30 W.P.M.',
    nameMarathi: 'मराठी Typing — ३० W.P.M.',
    badge: '',
    isCombo: false,
    isTyping: true,
    typingLang: 'Marathi',
    typingSpeed: '30 W.P.M.',
    duration: '3 Months',
    fees: null,
    shortDesc: 'मराठी Typing 30 Words Per Minute — Marathi typing certificate.',
  },
  {
    id: 'marathi-typing-40',
    category: 'typing',
    icon: '⌨️',
    name: 'Certificate in Computer Based Marathi Typing - 40 W.P.M.',
    nameMarathi: 'मराठी Typing — ४० W.P.M.',
    badge: '',
    isCombo: false,
    isTyping: true,
    typingLang: 'Marathi',
    typingSpeed: '40 W.P.M.',
    duration: '3 Months',
    fees: null,
    shortDesc: 'मराठी Typing 40 Words Per Minute — advanced speed certificate.',
  },
  {
    id: 'hindi-typing-30',
    category: 'typing',
    icon: '⌨️',
    name: 'Certificate in Computer Based Hindi Typing - 30 W.P.M.',
    nameMarathi: 'हिंदी Typing — 30 W.P.M.',
    badge: '',
    isCombo: false,
    isTyping: true,
    typingLang: 'Hindi',
    typingSpeed: '30 W.P.M.',
    duration: '3 Months',
    fees: null,
    shortDesc: 'हिंदी Typing 30 Words Per Minute — Hindi typing certificate.',
  },
  {
    id: 'hindi-typing-40',
    category: 'typing',
    icon: '⌨️',
    name: 'Certificate in Computer Based Hindi Typing - 40 W.P.M.',
    nameMarathi: 'हिंदी Typing — 40 W.P.M.',
    badge: '',
    isCombo: false,
    isTyping: true,
    typingLang: 'Hindi',
    typingSpeed: '40 W.P.M.',
    duration: '3 Months',
    fees: null,
    shortDesc: 'हिंदी Typing 40 Words Per Minute — advanced speed certificate.',
  },
  {
    id: 'gcc-tbc',
    category: 'typing',
    icon: '🎯',
    name: 'GCC-TBC Pune Board Typing (Any One)',
    nameMarathi: 'GCC-TBC Pune Board Typing',
    badge: 'Board Exam',
    isCombo: false,
    isTyping: true,
    typingCombos: [
      'English 30 + English 40',
      'Marathi 30 + Marathi 40',
      'Hindi 30 + Hindi 40',
    ],
    typingSpeed: null,
    duration: '6 Months',
    fees: null,
    shortDesc: 'GCC-TBC Pune Board Typing — English, Marathi किंवा Hindi मधून एक combination निवडा.',
  },
  // ── Diploma ───────────────────────────────────────────────
  {
    id: 'diploma',
    category: 'computer',
    icon: '🎓',
    name: 'DIPLOMA',
    nameMarathi: 'डिप्लोमा',
    badge: 'Diploma',
    isCombo: false,
    duration: null,
    fees: null,
    shortDesc: 'Diploma in Computer Applications — comprehensive computer skills diploma program.',
  },

  // ── All courses from official course list (317 entries, duplicates removed) ──

  // Computer Fundamentals & Basic
  { id: 'cert-it-proficiency',           category: 'computer',    icon: '💻', name: 'Certificate in IT Proficiency',                                    duration: '2 Months',  fees: null, shortDesc: 'IT Proficiency certificate course.' },
  { id: 'cert-computer-fundamentals',    category: 'computer',    icon: '💻', name: 'Certificate in Computer Fundamentals',                             duration: '3 Months',  fees: null, shortDesc: 'Computer fundamentals certificate.' },
  { id: 'adv-cert-computer-fundamentals',category: 'computer',    icon: '💻', name: 'Advance Certificate in Computer Fundamentals',                     duration: '3 Months',  fees: null, shortDesc: 'Advanced computer fundamentals.' },
  { id: 'cert-basic-computer',           category: 'computer',    icon: '💻', name: 'Certificate in Basic Computer Course',                             duration: '3 Months',  fees: null, shortDesc: 'Basic computer course certificate.' },
  { id: 'cert-basic-computer-1m',        category: 'computer',    icon: '💻', name: 'Certificate in Basic Computer Course (1 Month)',                   duration: '1 Month',   fees: null, shortDesc: 'One month basic computer certificate.' },
  { id: 'cert-computer-concept',         category: 'computer',    icon: '💻', name: 'Certificate in Computer Concept',                                  duration: '3 Months',  fees: null, shortDesc: 'Computer concepts certificate.' },
  { id: 'cert-computer-fundamentals-html',category: 'computer',   icon: '💻', name: 'Certificate in Advance Computer Fundamentals and HTML',            duration: '3 Months',  fees: null, shortDesc: 'Advanced fundamentals with HTML.' },
  { id: 'cert-info-tech',                category: 'computer',    icon: '💻', name: 'Certificate in Information Technology',                            duration: '3 Months',  fees: null, shortDesc: 'Information technology certificate.' },
  { id: 'cert-ict',                      category: 'computer',    icon: '💻', name: 'Certificate in Information Communication Technology',              duration: '3 Months',  fees: null, shortDesc: 'ICT certificate course.' },
  { id: 'cert-computer-applications',    category: 'computer',    icon: '💻', name: 'Certificate in Computer Applications',                             duration: '3 Months',  fees: null, shortDesc: 'Computer applications certificate.' },
  { id: 'cert-computer-applications-6m', category: 'computer',    icon: '💻', name: 'Certificate in Computer Applications (6 Months)',                  duration: '6 Months',  fees: null, shortDesc: 'Six month computer applications.' },
  { id: 'cert-computer-applications-120h',category: 'computer',   icon: '💻', name: 'Certificate in Computer Applications (120 Hours)',                 duration: '120 Hours', fees: null, shortDesc: 'Computer applications 120 hours.' },
  { id: 'cert-fundamentals-internet',    category: 'computer',    icon: '💻', name: 'Certificate in Fundamentals of Computer and Internet',             duration: '3 Months',  fees: null, shortDesc: 'Computer fundamentals and internet.' },
  { id: 'cert-internet-usage',           category: 'computer',    icon: '🌐', name: 'Certificate in Internet Usage and Utility',                        duration: '2 Months',  fees: null, shortDesc: 'Internet usage and utility.' },
  { id: 'cert-computer-operator',        category: 'computer',    icon: '💻', name: 'Certificate in Computer Operator',                                 duration: '6 Months',  fees: null, shortDesc: 'Computer operator certificate.' },
  { id: 'cert-data-entry-operator',      category: 'computer',    icon: '💻', name: 'Certificate in Data Entry Operator',                               duration: '6 Months',  fees: null, shortDesc: 'Data entry operator certificate.' },
  { id: 'cert-pc-technician',            category: 'computer',    icon: '🔧', name: 'Certificate in PC Technician',                                     duration: '45 Days',   fees: null, shortDesc: 'PC technician certificate.' },
  { id: 'cert-computer-hardware',        category: 'computer',    icon: '🔧', name: 'Certificate in Computer Hardware',                                 duration: '3 Months',  fees: null, shortDesc: 'Computer hardware certificate.' },
  { id: 'cert-computer-networking',      category: 'computer',    icon: '🔧', name: 'Certificate in Computer Networking',                               duration: '3 Months',  fees: null, shortDesc: 'Computer networking certificate.' },
  { id: 'cert-adv-networking',           category: 'computer',    icon: '🔧', name: 'Certificate in Advance Networking',                                duration: '3 Months',  fees: null, shortDesc: 'Advanced networking certificate.' },

  // MS Office & Office Automation
  { id: 'cert-ms-office-internet',       category: 'computer',    icon: '📄', name: 'Certificate in MS Office and Internet',                           duration: '3 Months',  fees: null, shortDesc: 'MS Office and internet certificate.' },
  { id: 'cert-ms-office-2m',             category: 'computer',    icon: '📄', name: 'Certificate in MS Office (2 Months)',                             duration: '2 Months',  fees: null, shortDesc: 'MS Office 2 month certificate.' },
  { id: 'cert-ms-office-3m',             category: 'computer',    icon: '📄', name: 'Certificate in MS Office (3 Months)',                             duration: '3 Months',  fees: null, shortDesc: 'MS Office 3 month certificate.' },
  { id: 'cert-ms-office-40h',            category: 'computer',    icon: '📄', name: 'Certificate in MS Office (40 Hours)',                             duration: '40 Hours',  fees: null, shortDesc: 'MS Office 40 hours certificate.' },
  { id: 'adv-cert-ms-office-internet',   category: 'computer',    icon: '📄', name: 'Advance Certificate in MS Office and Internet',                   duration: '3 Months',  fees: null, shortDesc: 'Advanced MS Office and internet.' },
  { id: 'cert-office-automation',        category: 'computer',    icon: '📄', name: 'Certificate in Office Automation',                                duration: '3 Months',  fees: null, shortDesc: 'Office automation certificate.' },
  { id: 'cert-office-professional',      category: 'computer',    icon: '📄', name: 'Certificate in Office Professional',                              duration: '3 Months',  fees: null, shortDesc: 'Office professional certificate.' },

  // Accounting & Tally
  { id: 'cert-computerized-accounting',  category: 'accounting',  icon: '🧾', name: 'Certificate in Computerized Accounting',                          duration: '3 Months',  fees: null, shortDesc: 'Computerized accounting certificate.' },
  { id: 'cert-accounting-taxation',      category: 'accounting',  icon: '🧾', name: 'Certificate in Accounting and Taxation',                          duration: '3 Months',  fees: null, shortDesc: 'Accounting and taxation certificate.' },
  { id: 'cert-financial-accounting',     category: 'accounting',  icon: '🧾', name: 'Certificate in Financial Accounting',                             duration: '3 Months',  fees: null, shortDesc: 'Financial accounting certificate.' },
  { id: 'cert-financial-accounting-mgmt',category: 'accounting',  icon: '🧾', name: 'Certificate in Financial Accounting Management',                  duration: '3 Months',  fees: null, shortDesc: 'Financial accounting management.' },
  { id: 'adv-cert-financial-accounting', category: 'accounting',  icon: '🧾', name: 'Advance Certificate in Financial Accounting',                     duration: '3 Months',  fees: null, shortDesc: 'Advanced financial accounting.' },
  { id: 'cert-tally-erp9-gst',           category: 'accounting',  icon: '🧾', name: 'Certificate in Tally.ERP 9 with GST',                             duration: '3 Months',  fees: null, shortDesc: 'Tally ERP9 with GST certificate.' },
  { id: 'cert-tally-erp9',               category: 'accounting',  icon: '🧾', name: 'Certificate in Tally.ERP9 Advanced',                              duration: '4 Months',  fees: null, shortDesc: 'Tally ERP9 advanced certificate.' },
  { id: 'cert-financial-accounting-tally',category: 'accounting', icon: '🧾', name: 'Certificate in Financial Accounting with Tally.ERP9',             duration: '3 Months',  fees: null, shortDesc: 'Financial accounting with Tally ERP9.' },
  { id: 'cert-computerized-accounting-gst',category: 'accounting',icon: '🧾', name: 'Certificate in Computerized Accounting with GST',                 duration: '3 Months',  fees: null, shortDesc: 'Computerized accounting with GST.' },
  { id: 'cert-account-expert-tally-prime',category: 'accounting', icon: '🧾', name: 'Certificate in Account Expert with Tally Prime',                  duration: '4 Months',  fees: null, shortDesc: 'Account expert with Tally Prime.' },
  { id: 'cert-tally-prime',              category: 'accounting',  icon: '🧾', name: 'Certificate in Tally Prime',                                      duration: '6 Months',  fees: null, shortDesc: 'Tally Prime certificate.' },
  { id: 'cert-tally-prime-gst-3m',       category: 'accounting',  icon: '🧾', name: 'Certificate in Tally Prime with GST (3 Months)',                  duration: '3 Months',  fees: null, shortDesc: 'Tally Prime with GST 3 months.' },
  { id: 'cert-adv-tally-prime-gst',      category: 'accounting',  icon: '🧾', name: 'Certificate in Advanced Tally Prime with GST',                    duration: '3 Months',  fees: null, shortDesc: 'Advanced Tally Prime with GST.' },
  { id: 'cert-smart-tally',              category: 'accounting',  icon: '🧾', name: 'Certificate in Smart Tally',                                      duration: '3 Months',  fees: null, shortDesc: 'Smart Tally certificate.' },
  { id: 'cert-basic-tally-prime',        category: 'accounting',  icon: '🧾', name: 'Certificate in Basic of Tally Prime',                             duration: '1 Month',   fees: null, shortDesc: 'Basics of Tally Prime.' },
  { id: 'cert-busy-accounting',          category: 'accounting',  icon: '🧾', name: 'Certificate in BUSY - Accounting Software',                       duration: '3 Months',  fees: null, shortDesc: 'BUSY accounting software certificate.' },
  { id: 'cert-gst',                      category: 'accounting',  icon: '🧾', name: 'Certificate in Indian Goods and Service Tax',                     duration: '1 Month',   fees: null, shortDesc: 'GST certificate course.' },
  { id: 'cert-sap-finance',              category: 'accounting',  icon: '🧾', name: 'Certificate in SAP Finance',                                      duration: '5 Months',  fees: null, shortDesc: 'SAP finance certificate.' },
  { id: 'cert-sap-fico',                 category: 'accounting',  icon: '🧾', name: 'Certificate in SAP - Finance and Controlling',                    duration: '5 Months',  fees: null, shortDesc: 'SAP FICO certificate.' },

  // Programming
  { id: 'cert-c-programming',            category: 'computer',    icon: '👨‍💻', name: 'Certificate in C Programming',                                    duration: '2 Months',  fees: null, shortDesc: 'C programming certificate.' },
  { id: 'cert-intro-c-programming',      category: 'computer',    icon: '👨‍💻', name: 'Certificate in Introduction to C Programming',                    duration: '3 Months',  fees: null, shortDesc: 'Introduction to C programming.' },
  { id: 'cert-c-programming-3m',         category: 'computer',    icon: '👨‍💻', name: 'Certificate in Programming in C',                                 duration: '3 Months',  fees: null, shortDesc: 'C programming 3 months.' },
  { id: 'cert-cpp',                      category: 'computer',    icon: '👨‍💻', name: 'Certificate in C++',                                              duration: '2 Months',  fees: null, shortDesc: 'C++ programming certificate.' },
  { id: 'cert-cpp-20days',               category: 'computer',    icon: '👨‍💻', name: 'Certificate in C++ (20 Days)',                                    duration: '20 Days',   fees: null, shortDesc: 'C++ 20 day course.' },
  { id: 'cert-cpp-programming',          category: 'computer',    icon: '👨‍💻', name: 'Certificate in C++ Programming',                                  duration: '3 Months',  fees: null, shortDesc: 'C++ programming certificate.' },
  { id: 'cert-oops-cpp',                 category: 'computer',    icon: '👨‍💻', name: 'Certificate in Object Oriented Programming using C++',            duration: '3 Months',  fees: null, shortDesc: 'OOP using C++ certificate.' },
  { id: 'cert-c-and-cpp',               category: 'computer',    icon: '👨‍💻', name: 'Certificate in C and C++',                                        duration: '3 Months',  fees: null, shortDesc: 'C and C++ combined certificate.' },
  { id: 'cert-java-core',               category: 'computer',    icon: '👨‍💻', name: 'Certificate in Java - Core',                                      duration: '3 Months',  fees: null, shortDesc: 'Java core certificate.' },
  { id: 'cert-java-advance',            category: 'computer',    icon: '👨‍💻', name: 'Certificate in Java - Advance',                                   duration: '3 Months',  fees: null, shortDesc: 'Java advanced certificate.' },
  { id: 'cert-java-programming',        category: 'computer',    icon: '👨‍💻', name: 'Certificate in Java Programming',                                 duration: '3 Months',  fees: null, shortDesc: 'Java programming certificate.' },
  { id: 'cert-java-springboot',         category: 'computer',    icon: '👨‍💻', name: 'Certificate in Java Spring Boot REST API Development',            duration: '90 Hours',  fees: null, shortDesc: 'Java Spring Boot REST API.' },
  { id: 'cert-python',                  category: 'computer',    icon: '🐍', name: 'Certificate in Python',                                            duration: '2 Months',  fees: null, shortDesc: 'Python programming certificate.' },
  { id: 'cert-python-computing',        category: 'computer',    icon: '🐍', name: 'Certificate in Computing - Python',                                duration: '3 Months',  fees: null, shortDesc: 'Python computing certificate.' },
  { id: 'cert-data-analysis-python',    category: 'computer',    icon: '🐍', name: 'Certificate in Data Analysis with Python',                         duration: '2 Months',  fees: null, shortDesc: 'Data analysis with Python.' },
  { id: 'cert-vb',                      category: 'computer',    icon: '👨‍💻', name: 'Certificate in Visual Basic',                                     duration: '3 Months',  fees: null, shortDesc: 'Visual Basic certificate.' },
  { id: 'cert-vbnet',                   category: 'computer',    icon: '👨‍💻', name: 'Certificate in VB.NET Programming',                               duration: '3 Months',  fees: null, shortDesc: 'VB.NET programming certificate.' },
  { id: 'cert-aspnet',                  category: 'computer',    icon: '👨‍💻', name: 'Certificate in ASP.NET Programming',                              duration: '3 Months',  fees: null, shortDesc: 'ASP.NET programming certificate.' },
  { id: 'cert-aspnet-mvc',              category: 'computer',    icon: '👨‍💻', name: 'Certificate in ASP.NET with MVC',                                 duration: '1 Month',   fees: null, shortDesc: 'ASP.NET with MVC certificate.' },
  { id: 'cert-csharp',                  category: 'computer',    icon: '👨‍💻', name: 'Certificate in C# .NET Programming',                              duration: '3 Months',  fees: null, shortDesc: 'C# .NET programming certificate.' },
  { id: 'cert-windows-adonet',          category: 'computer',    icon: '👨‍💻', name: 'Certificate in Windows App and ADO.NET',                          duration: '1 Month',   fees: null, shortDesc: 'Windows app and ADO.NET.' },
  { id: 'cert-android',                 category: 'computer',    icon: '📱', name: 'Certificate in Android Application Development',                   duration: '3 Months',  fees: null, shortDesc: 'Android app development.' },
  { id: 'cert-react-mobile',            category: 'computer',    icon: '📱', name: 'Certificate in Mobile App Development with React',                 duration: '2 Months',  fees: null, shortDesc: 'Mobile app with React.' },
  { id: 'cert-react-frontend',          category: 'computer',    icon: '⚛️', name: 'Certificate in React Front End Development',                       duration: '90 Hours',  fees: null, shortDesc: 'React front end development.' },
  { id: 'cert-scratch',                 category: 'computer',    icon: '👨‍💻', name: 'Certificate in Scratch Programming',                              duration: '2 Months',  fees: null, shortDesc: 'Scratch programming certificate.' },
  { id: 'cert-data-structures',         category: 'computer',    icon: '👨‍💻', name: 'Certificate in Data Structures',                                  duration: '3 Months',  fees: null, shortDesc: 'Data structures certificate.' },
  { id: 'cert-data-structures-algo',    category: 'computer',    icon: '👨‍💻', name: 'Certificate in Data Structures and Algorithms',                   duration: '4 Months',  fees: null, shortDesc: 'Data structures and algorithms.' },
  { id: 'cert-dbms',                    category: 'computer',    icon: '🗄️', name: 'Certificate in Database Management Systems',                       duration: '3 Months',  fees: null, shortDesc: 'DBMS certificate.' },
  { id: 'cert-sql',                     category: 'computer',    icon: '🗄️', name: 'Certificate in SQL',                                               duration: '2 Months',  fees: null, shortDesc: 'SQL certificate.' },
  { id: 'cert-mysql',                   category: 'computer',    icon: '🗄️', name: 'Certificate in My SQL',                                            duration: '3 Months',  fees: null, shortDesc: 'MySQL certificate.' },
  { id: 'cert-oracle-sql',              category: 'computer',    icon: '🗄️', name: 'Certificate in Oracle SQL and PLSQL',                              duration: '4 Months',  fees: null, shortDesc: 'Oracle SQL and PLSQL.' },
  { id: 'cert-operating-systems',       category: 'computer',    icon: '💻', name: 'Certificate in Operating Systems',                                  duration: '3 Months',  fees: null, shortDesc: 'Operating systems certificate.' },
  { id: 'cert-software-testing',        category: 'computer',    icon: '🧪', name: 'Certificate in Software Testing',                                  duration: '3 Months',  fees: null, shortDesc: 'Software testing certificate.' },
  { id: 'cert-ethical-hacking',         category: 'computer',    icon: '🔐', name: 'Certificate in Ethical Hacking',                                  duration: '2 Months',  fees: null, shortDesc: 'Ethical hacking certificate.' },
  { id: 'cert-ai',                      category: 'computer',    icon: '🤖', name: 'Certificate in Artificial Intelligence',                           duration: '3 Months',  fees: null, shortDesc: 'Artificial intelligence certificate.' },
  { id: 'cert-iot-arduino',             category: 'computer',    icon: '🤖', name: 'Certificate in IOT with Arduino',                                  duration: '3 Months',  fees: null, shortDesc: 'IOT with Arduino certificate.' },
  { id: 'cert-chatgpt',                 category: 'computer',    icon: '🤖', name: 'Certificate in ChatGPT',                                           duration: '1 Month',   fees: null, shortDesc: 'ChatGPT certificate.' },
  { id: 'cert-office-automation-ai',    category: 'computer',    icon: '🤖', name: 'Certificate in Office Automation with AI',                         duration: '3 Months',  fees: null, shortDesc: 'Office automation with AI.' },

  // Web Development
  { id: 'cert-html',                    category: 'computer',    icon: '🌐', name: 'Certificate in HTML',                                              duration: '3 Months',  fees: null, shortDesc: 'HTML certificate.' },
  { id: 'cert-html5',                   category: 'computer',    icon: '🌐', name: 'Certificate in HTML5',                                             duration: '1 Month',   fees: null, shortDesc: 'HTML5 certificate.' },
  { id: 'cert-css',                     category: 'computer',    icon: '🌐', name: 'Certificate in Cascading Style Sheets',                            duration: '1 Month',   fees: null, shortDesc: 'CSS certificate.' },
  { id: 'cert-html-css',                category: 'computer',    icon: '🌐', name: 'Certificate in HTML and CSS',                                      duration: '3 Months',  fees: null, shortDesc: 'HTML and CSS certificate.' },
  { id: 'cert-javascript',              category: 'computer',    icon: '🌐', name: 'Certificate in Java Script',                                       duration: '1 Month',   fees: null, shortDesc: 'JavaScript certificate.' },
  { id: 'cert-jquery',                  category: 'computer',    icon: '🌐', name: 'Certificate in jQuery and jQuery-UI',                              duration: '1 Month',   fees: null, shortDesc: 'jQuery and jQuery-UI certificate.' },
  { id: 'cert-bootstrap',               category: 'computer',    icon: '🌐', name: 'Certificate in Bootstrap',                                        duration: '1 Month',   fees: null, shortDesc: 'Bootstrap certificate.' },
  { id: 'cert-angularjs',               category: 'computer',    icon: '🌐', name: 'Certificate in Angular JS',                                       duration: '1 Month',   fees: null, shortDesc: 'Angular JS certificate.' },
  { id: 'cert-angular',                 category: 'computer',    icon: '🌐', name: 'Certificate in Angular',                                          duration: '2 Months',  fees: null, shortDesc: 'Angular certificate.' },
  { id: 'cert-php',                     category: 'computer',    icon: '🌐', name: 'Certificate in PHP',                                              duration: '2 Months',  fees: null, shortDesc: 'PHP certificate.' },
  { id: 'cert-php-mysql',               category: 'computer',    icon: '🌐', name: 'Certificate in PHP and MySQL',                                    duration: '2 Months',  fees: null, shortDesc: 'PHP and MySQL certificate.' },
  { id: 'cert-web-design-foundation',   category: 'computer',    icon: '🌐', name: 'Certificate in Web Designing - Foundation',                       duration: '3 Months',  fees: null, shortDesc: 'Web designing foundation.' },
  { id: 'cert-professional-web-design', category: 'computer',    icon: '🌐', name: 'Certificate in Professional Web Designing',                       duration: '3 Months',  fees: null, shortDesc: 'Professional web designing.' },
  { id: 'cert-professional-web-dev',    category: 'computer',    icon: '🌐', name: 'Certificate in Professional Web Developer',                       duration: '3 Months',  fees: null, shortDesc: 'Professional web developer.' },
  { id: 'cert-web-tech-multimedia',     category: 'computer',    icon: '🌐', name: 'Certificate in Web Technologies and Multimedia',                  duration: '3 Months',  fees: null, shortDesc: 'Web technologies and multimedia.' },
  { id: 'cert-digital-marketing',       category: 'computer',    icon: '📢', name: 'Certificate in Digital Marketing',                                duration: '3 Months',  fees: null, shortDesc: 'Digital marketing certificate.' },
  { id: 'cert-google-data-studio',      category: 'computer',    icon: '📊', name: 'Certificate in Google Data Studio',                               duration: '2 Months',  fees: null, shortDesc: 'Google Data Studio certificate.' },
  { id: 'cert-power-bi-3m',             category: 'computer',    icon: '📊', name: 'Certificate in Microsoft Power BI (3 Months)',                    duration: '3 Months',  fees: null, shortDesc: 'Microsoft Power BI 3 months.' },
  { id: 'cert-power-bi-1m',             category: 'computer',    icon: '📊', name: 'Certificate in Microsoft Power BI (1 Month)',                     duration: '1 Month',   fees: null, shortDesc: 'Microsoft Power BI 1 month.' },

  // Design & Creative
  { id: 'cert-photoshop',               category: 'design',      icon: '🎨', name: 'Certificate in Photoshop',                                        duration: '2 Months',  fees: null, shortDesc: 'Photoshop certificate.' },
  { id: 'cert-corel-draw',              category: 'design',      icon: '🎨', name: 'Certificate in Corel Draw',                                       duration: '2 Months',  fees: null, shortDesc: 'Corel Draw certificate.' },
  { id: 'cert-adobe-illustrator',       category: 'design',      icon: '🎨', name: 'Certificate in Adobe Illustrator',                                duration: '2 Months',  fees: null, shortDesc: 'Adobe Illustrator certificate.' },
  { id: 'cert-computer-graphics',       category: 'design',      icon: '🎨', name: 'Certificate in Computer Graphics',                                duration: '3 Months',  fees: null, shortDesc: 'Computer graphics certificate.' },
  { id: 'cert-video-editing',           category: 'design',      icon: '🎬', name: 'Certificate in Video Editing',                                    duration: '2 Months',  fees: null, shortDesc: 'Video editing certificate.' },
  { id: 'cert-digital-photography',     category: 'design',      icon: '📷', name: 'Certificate in Digital Photography',                              duration: '3 Months',  fees: null, shortDesc: 'Digital photography certificate.' },
  { id: 'cert-vray',                    category: 'design',      icon: '🎨', name: 'Certificate in V-RAY',                                            duration: '2 Months',  fees: null, shortDesc: 'V-RAY rendering certificate.' },
  { id: 'cert-lumion',                  category: 'design',      icon: '🎨', name: 'Certificate in Lumion',                                           duration: '1 Month',   fees: null, shortDesc: 'Lumion certificate.' },
  { id: 'cert-3dsmax',                  category: 'design',      icon: '🎨', name: 'Certificate in 3D S MAX',                                         duration: '3 Months',  fees: null, shortDesc: '3D Studio MAX certificate.' },

  // CAD / Engineering
  { id: 'cert-autocad-2m',              category: 'design',      icon: '📐', name: 'Certificate in AutoCAD (2 Months)',                               duration: '2 Months',  fees: null, shortDesc: 'AutoCAD 2 months certificate.' },
  { id: 'cert-autocad-45d',             category: 'design',      icon: '📐', name: 'Certificate in AutoCAD (45 Days)',                                duration: '45 Days',   fees: null, shortDesc: 'AutoCAD 45 days certificate.' },
  { id: 'cert-autocad-20d',             category: 'design',      icon: '📐', name: 'Certificate in AutoCAD (20 Days)',                                duration: '20 Days',   fees: null, shortDesc: 'AutoCAD 20 days certificate.' },
  { id: 'cert-professional-autocad',    category: 'design',      icon: '📐', name: 'Certificate in Professional AutoCAD',                             duration: '3 Months',  fees: null, shortDesc: 'Professional AutoCAD certificate.' },
  { id: 'cert-2d-autocad',              category: 'design',      icon: '📐', name: 'Certificate in 2D AutoCAD',                                      duration: '2 Months',  fees: null, shortDesc: '2D AutoCAD certificate.' },
  { id: 'cert-3d-autocad',              category: 'design',      icon: '📐', name: 'Certificate in 3D AutoCAD',                                      duration: '2 Months',  fees: null, shortDesc: '3D AutoCAD certificate.' },
  { id: 'cert-cad',                     category: 'design',      icon: '📐', name: 'Certificate in CAD',                                              duration: '3 Months',  fees: null, shortDesc: 'CAD certificate.' },
  { id: 'cert-catia',                   category: 'design',      icon: '📐', name: 'Certificate in CATIA V5',                                         duration: '1.5 Months',fees: null, shortDesc: 'CATIA V5 certificate.' },
  { id: 'cert-revit',                   category: 'design',      icon: '📐', name: 'Certificate in Revit Architecture',                               duration: '2 Months',  fees: null, shortDesc: 'Revit architecture certificate.' },
  { id: 'cert-staad-pro',               category: 'design',      icon: '📐', name: 'Certificate in STAAD.PRO',                                        duration: '1 Month',   fees: null, shortDesc: 'STAAD.PRO certificate.' },
  { id: 'cert-etabs',                   category: 'design',      icon: '📐', name: 'Certificate in ETABS',                                            duration: '45 Days',   fees: null, shortDesc: 'ETABS certificate.' },
  { id: 'cert-solidworks',              category: 'design',      icon: '📐', name: 'Certificate in SolidWorks',                                       duration: '2 Months',  fees: null, shortDesc: 'SolidWorks certificate.' },
  { id: 'cert-creo',                    category: 'design',      icon: '📐', name: 'Certificate in Creo',                                             duration: '3 Months',  fees: null, shortDesc: 'Creo certificate.' },
  { id: 'cert-proe',                    category: 'design',      icon: '📐', name: 'Certificate in PRO-E',                                            duration: '3 Months',  fees: null, shortDesc: 'PRO-E certificate.' },
  { id: 'cert-unigraphics',             category: 'design',      icon: '📐', name: 'Certificate in Unigraphics NX',                                   duration: '2 Months',  fees: null, shortDesc: 'Unigraphics NX certificate.' },
  { id: 'cert-sketchup',                category: 'design',      icon: '📐', name: 'Certificate in SketchUp',                                         duration: '3 Months',  fees: null, shortDesc: 'SketchUp certificate.' },
  { id: 'cert-bim-engineering',         category: 'design',      icon: '📐', name: 'Certificate in BIM Engineering',                                  duration: '6 Months',  fees: null, shortDesc: 'BIM engineering certificate.' },
  { id: 'cert-primavera',               category: 'design',      icon: '📐', name: 'Certificate in Primavera',                                        duration: '2 Months',  fees: null, shortDesc: 'Primavera certificate.' },
  { id: 'cert-estimate-costing',        category: 'design',      icon: '📐', name: 'Certificate in Estimate and Costing in Civil Engineering',        duration: '1 Month',   fees: null, shortDesc: 'Estimate and costing in civil engineering.' },
  { id: 'cert-ansys',                   category: 'design',      icon: '📐', name: 'Certificate in Engineering Analysis with ANSYS',                  duration: '3 Months',  fees: null, shortDesc: 'ANSYS engineering analysis.' },
  { id: 'cert-cnc-operating',           category: 'computer',    icon: '⚙️', name: 'Certificate in CNC Operating',                                   duration: '3 Months',  fees: null, shortDesc: 'CNC operating certificate.' },
  { id: 'cert-cnc-operating-programming',category: 'computer',   icon: '⚙️', name: 'Certificate in CNC Operating and Programming',                   duration: '6 Months',  fees: null, shortDesc: 'CNC operating and programming.' },

  // Typing (additional)
  { id: 'cert-eng-typing-50wpm',        category: 'typing',      icon: '⌨️', name: 'Certificate in Computer Based English Typing - 50 W.P.M.',       duration: '6 Months',  fees: null, shortDesc: 'English typing 50 WPM certificate.' },
  { id: 'cert-eng-typing-60wpm',        category: 'typing',      icon: '⌨️', name: 'Certificate in Computer Based English Typing - 60 W.P.M.',       duration: '6 Months',  fees: null, shortDesc: 'English typing 60 WPM certificate.' },
  { id: 'cert-hindi-typing-50wpm',      category: 'typing',      icon: '⌨️', name: 'Certificate in Computer Based Hindi Typing - 50 W.P.M.',         duration: '6 Months',  fees: null, shortDesc: 'Hindi typing 50 WPM certificate.' },
  { id: 'cert-hindi-typing-60wpm',      category: 'typing',      icon: '⌨️', name: 'Certificate in Computer Based Hindi Typing - 60 W.P.M.',         duration: '6 Months',  fees: null, shortDesc: 'Hindi typing 60 WPM certificate.' },
  { id: 'cert-shorthand-eng',           category: 'typing',      icon: '⌨️', name: 'Certificate in Shorthand 100 W.P.M. - English',                  duration: '1 Year',    fees: null, shortDesc: 'English shorthand 100 WPM.' },

  // Diploma courses
  { id: 'dip-software-application',     category: 'computer',    icon: '🎓', name: 'Diploma in Software Application',                                 duration: '6 Months',  fees: null, shortDesc: 'Software application diploma.' },
  { id: 'dip-information-technology',   category: 'computer',    icon: '🎓', name: 'Diploma in Information Technology',                               duration: '6 Months',  fees: null, shortDesc: 'Information technology diploma.' },
  { id: 'dip-office-automation',        category: 'computer',    icon: '🎓', name: 'Diploma in Office Automation',                                    duration: '6 Months',  fees: null, shortDesc: 'Office automation diploma.' },
  { id: 'dip-office-management',        category: 'computer',    icon: '🎓', name: 'Diploma in Office Management',                                    duration: '6 Months',  fees: null, shortDesc: 'Office management diploma.' },
  { id: 'dip-office-management-tally',  category: 'accounting',  icon: '🎓', name: 'Diploma in Office Management with Tally',                         duration: '6 Months',  fees: null, shortDesc: 'Office management with Tally diploma.' },
  { id: 'dip-office-automation-pub',    category: 'computer',    icon: '🎓', name: 'Diploma in Office Automation and Publishing',                     duration: '1 Year',    fees: null, shortDesc: 'Office automation and publishing diploma.' },
  { id: 'dip-computer-software',        category: 'computer',    icon: '🎓', name: 'Diploma in Computer Software',                                    duration: '6 Months',  fees: null, shortDesc: 'Computer software diploma.' },
  { id: 'dip-computer-application-6m',  category: 'computer',    icon: '🎓', name: 'Diploma in Computer Application (6 Months)',                      duration: '6 Months',  fees: null, shortDesc: 'Computer application diploma 6 months.' },
  { id: 'dip-computer-application-1y',  category: 'computer',    icon: '🎓', name: 'Diploma in Computer Application (1 Year)',                        duration: '1 Year',    fees: null, shortDesc: 'Computer application diploma 1 year.' },
  { id: 'dip-computer-operator',        category: 'computer',    icon: '🎓', name: 'Diploma in Computer Operator',                                    duration: '6 Months',  fees: null, shortDesc: 'Computer operator diploma.' },
  { id: 'dip-computer-concept',         category: 'computer',    icon: '🎓', name: 'Diploma in Computer Concept',                                     duration: '6 Months',  fees: null, shortDesc: 'Computer concept diploma.' },
  { id: 'dip-data-entry-operator',      category: 'computer',    icon: '🎓', name: 'Diploma in Data Entry Operator',                                  duration: '1 Year',    fees: null, shortDesc: 'Data entry operator diploma.' },
  { id: 'dip-computer-dtp',             category: 'computer',    icon: '🎓', name: 'Diploma in Computer Application and DTP',                         duration: '1 Year',    fees: null, shortDesc: 'Computer application and DTP diploma.' },
  { id: 'dip-application-software',     category: 'computer',    icon: '🎓', name: 'Diploma in Application Software',                                 duration: '6 Months',  fees: null, shortDesc: 'Application software diploma.' },
  { id: 'dip-computer-digital',         category: 'computer',    icon: '🎓', name: 'Diploma in Computer and Digital Application',                     duration: '6 Months',  fees: null, shortDesc: 'Computer and digital application diploma.' },
  { id: 'dip-computer-business-mgmt',   category: 'computer',    icon: '🎓', name: 'Diploma in Computer Business Management',                         duration: '6 Months',  fees: null, shortDesc: 'Computer business management diploma.' },
  { id: 'dip-computer-education',       category: 'computer',    icon: '🎓', name: 'Diploma in Computer Education',                                   duration: '1 Year',    fees: null, shortDesc: 'Computer education diploma.' },
  { id: 'dip-computer-operator-prog',   category: 'computer',    icon: '🎓', name: 'Diploma in Computer Operator and Programming Assistant',          duration: '1 Year',    fees: null, shortDesc: 'Computer operator and programming assistant.' },
  { id: 'dip-hardware-engineering',     category: 'computer',    icon: '🎓', name: 'Diploma in Hardware Engineering',                                 duration: '6 Months',  fees: null, shortDesc: 'Hardware engineering diploma.' },
  { id: 'dip-hardware-networking',      category: 'computer',    icon: '🎓', name: 'Diploma in Hardware and Networking',                              duration: '1 Year',    fees: null, shortDesc: 'Hardware and networking diploma.' },
  { id: 'dip-network-admin',            category: 'computer',    icon: '🎓', name: 'Diploma in Network Administration',                               duration: '6 Months',  fees: null, shortDesc: 'Network administration diploma.' },
  { id: 'dip-web-designing',            category: 'computer',    icon: '🎓', name: 'Diploma in Web Designing',                                        duration: '9 Months',  fees: null, shortDesc: 'Web designing diploma.' },
  { id: 'dip-web-designing-dev',        category: 'computer',    icon: '🎓', name: 'Diploma in Web Designing and Web Development',                    duration: '1 Year',    fees: null, shortDesc: 'Web designing and development diploma.' },
  { id: 'dip-full-stack-web',           category: 'computer',    icon: '🎓', name: 'Diploma in Full Stack Web Developer',                             duration: '6 Months',  fees: null, shortDesc: 'Full stack web developer diploma.' },
  { id: 'dip-software-dev',             category: 'computer',    icon: '🎓', name: 'Diploma in Software Development',                                 duration: '6 Months',  fees: null, shortDesc: 'Software development diploma.' },
  { id: 'dip-core-java-adv',            category: 'computer',    icon: '🎓', name: 'Diploma in Core Java and Advanced Java',                          duration: '6 Months',  fees: null, shortDesc: 'Core and advanced Java diploma.' },
  { id: 'dip-cyber-law',                category: 'computer',    icon: '🎓', name: 'Diploma in Cyber Law',                                            duration: '6 Months',  fees: null, shortDesc: 'Cyber law diploma.' },
  { id: 'dip-digital-marketing',        category: 'computer',    icon: '🎓', name: 'Diploma in Digital Marketing',                                    duration: '6 Months',  fees: null, shortDesc: 'Digital marketing diploma.' },
  { id: 'adv-dip-digital-marketing',    category: 'computer',    icon: '🎓', name: 'Advance Diploma in Digital Marketing',                            duration: '1 Year',    fees: null, shortDesc: 'Advanced digital marketing diploma.' },
  { id: 'dip-data-analyst',             category: 'computer',    icon: '🎓', name: 'Diploma in Data Analyst',                                         duration: '1 Year',    fees: null, shortDesc: 'Data analyst diploma.' },
  { id: 'dip-ai',                       category: 'computer',    icon: '🎓', name: 'Diploma in Artificial Intelligence',                              duration: '6 Months',  fees: null, shortDesc: 'Artificial intelligence diploma.' },
  { id: 'adv-dip-python',               category: 'computer',    icon: '🎓', name: 'Advance Diploma in Python',                                       duration: '8 Months',  fees: null, shortDesc: 'Advanced Python diploma.' },
  { id: 'adv-dip-it',                   category: 'computer',    icon: '🎓', name: 'Advance Diploma in Information Technology',                       duration: '6 Months',  fees: null, shortDesc: 'Advanced IT diploma.' },
  { id: 'adv-dip-it-1y',                category: 'computer',    icon: '🎓', name: 'Advance Diploma in Information Technology (1 Year)',               duration: '1 Year',    fees: null, shortDesc: 'Advanced IT diploma 1 year.' },
  { id: 'adv-dip-software-eng',         category: 'computer',    icon: '🎓', name: 'Advance Diploma in Software Engineering',                         duration: '1 Year',    fees: null, shortDesc: 'Advanced software engineering diploma.' },
  { id: 'adv-dip-software-app',         category: 'computer',    icon: '🎓', name: 'Advance Diploma in Computer Software',                            duration: '12 Months', fees: null, shortDesc: 'Advanced computer software diploma.' },
  { id: 'adv-dip-comp-app',             category: 'computer',    icon: '🎓', name: 'Advance Diploma in Computer Application',                         duration: '1 Year',    fees: null, shortDesc: 'Advanced computer application diploma.' },
  { id: 'adv-dip-comp-app-6m',          category: 'computer',    icon: '🎓', name: 'Advance Diploma in Computer Application (6 Months)',              duration: '6 Months',  fees: null, shortDesc: 'Advanced computer application 6 months.' },
  { id: 'adv-dip-comp-app-prog',        category: 'computer',    icon: '🎓', name: 'Advance Diploma in Computer Applications and Programming',        duration: '1 Year',    fees: null, shortDesc: 'Computer applications and programming diploma.' },
  { id: 'adv-dip-multimedia',           category: 'computer',    icon: '🎓', name: 'Advance Diploma in Multimedia Applications',                      duration: '1 Year',    fees: null, shortDesc: 'Multimedia applications diploma.' },
  { id: 'adv-dip-networking-cloud',     category: 'computer',    icon: '🎓', name: 'Advance Diploma in Computer Networking and Cloud Computing',      duration: '1 Year',    fees: null, shortDesc: 'Networking and cloud computing diploma.' },
  { id: 'master-cert-comp-app',         category: 'computer',    icon: '🎓', name: 'Master Certificate in Computer Applications and Advanced Accounting', duration: '6 Months', fees: null, shortDesc: 'Master certificate in computer applications.' },
  { id: 'master-dip-it',                category: 'computer',    icon: '🎓', name: 'Master Diploma in Information Technology',                        duration: '1 Year',    fees: null, shortDesc: 'Master diploma in IT.' },
  { id: 'master-dip-comp-app-acct',     category: 'computer',    icon: '🎓', name: 'Master Diploma in Computer Applications and Advanced Accounting',  duration: '1 Year',    fees: null, shortDesc: 'Master diploma in computer applications.' },
  { id: 'dip-computerized-accounting',  category: 'accounting',  icon: '🎓', name: 'Diploma in Computerized Accounting',                              duration: '6 Months',  fees: null, shortDesc: 'Computerized accounting diploma.' },
  { id: 'master-dip-comp-accounting',   category: 'accounting',  icon: '🎓', name: 'Master Diploma in Computerized Accounting',                       duration: '6 Months',  fees: null, shortDesc: 'Master diploma in computerized accounting.' },
  { id: 'dip-financial-accounting',     category: 'accounting',  icon: '🎓', name: 'Diploma in Financial Accounting',                                 duration: '9 Months',  fees: null, shortDesc: 'Financial accounting diploma.' },
  { id: 'dip-financial-accounting-6m',  category: 'accounting',  icon: '🎓', name: 'Diploma in Financial Accounting (6 Months)',                      duration: '6 Months',  fees: null, shortDesc: 'Financial accounting diploma 6 months.' },
  { id: 'dip-computerized-ind-acct',    category: 'accounting',  icon: '🎓', name: 'Diploma in Computerized Industrial Accounting',                   duration: '1 Year',    fees: null, shortDesc: 'Computerized industrial accounting diploma.' },
  { id: 'dip-tally-erp9-gst-1y',       category: 'accounting',  icon: '🎓', name: 'Diploma in Tally.ERP 9 with GST (1 Year)',                        duration: '1 Year',    fees: null, shortDesc: 'Tally ERP9 with GST diploma 1 year.' },
  { id: 'dip-tally-erp9-gst-6m',       category: 'accounting',  icon: '🎓', name: 'Diploma in Tally.ERP 9 with GST (6 Months)',                      duration: '6 Months',  fees: null, shortDesc: 'Tally ERP9 with GST diploma 6 months.' },
  { id: 'dip-tally-prime-gst',         category: 'accounting',  icon: '🎓', name: 'Diploma in Tally Prime with GST',                                 duration: '6 Months',  fees: null, shortDesc: 'Tally Prime with GST diploma.' },
  { id: 'dip-tally-professional',      category: 'accounting',  icon: '🎓', name: 'Diploma in Tally Professional',                                   duration: '6 Months',  fees: null, shortDesc: 'Tally professional diploma.' },
  { id: 'dip-comp-app-adv-acct',       category: 'accounting',  icon: '🎓', name: 'Diploma in Computer Applications and Advanced Accounting',        duration: '6 Months',  fees: null, shortDesc: 'Computer applications and advanced accounting.' },
  { id: 'dip-advance-excel',           category: 'accounting',  icon: '🎓', name: 'Diploma in Advance Excel',                                        duration: '1 Year',    fees: null, shortDesc: 'Advanced Excel diploma.' },
  { id: 'cert-advanced-excel-6m',      category: 'accounting',  icon: '📊', name: 'Certificate in Advanced Excel (6 Months)',                        duration: '6 Months',  fees: null, shortDesc: 'Advanced Excel 6 months certificate.' },
  { id: 'dip-graphic-design',          category: 'design',      icon: '🎨', name: 'Diploma in Graphic Design',                                       duration: '6 Months',  fees: null, shortDesc: 'Graphic design diploma.' },
  { id: 'dip-2d-3d-autocad',           category: 'design',      icon: '📐', name: 'Diploma in 2D and 3D AutoCAD',                                    duration: '6 Months',  fees: null, shortDesc: '2D and 3D AutoCAD diploma.' },
  { id: 'dip-2d-3d-animation',         category: 'design',      icon: '🎬', name: 'Diploma in 2D and 3D Animation',                                  duration: '6 Months',  fees: null, shortDesc: '2D and 3D animation diploma.' },
  { id: 'dip-digital-photography',     category: 'design',      icon: '📷', name: 'Diploma in Digital Photography',                                  duration: '1 Year',    fees: null, shortDesc: 'Digital photography diploma.' },
  { id: 'dip-uiux',                    category: 'design',      icon: '🎨', name: 'Diploma in UI/UX Design',                                         duration: '6 Months',  fees: null, shortDesc: 'UI/UX design diploma.' },
  { id: 'dip-architectural-design',    category: 'design',      icon: '📐', name: 'Diploma in Architectural Design and Creative Softwares',          duration: '6 Months',  fees: null, shortDesc: 'Architectural design and creative softwares.' },
  { id: 'dip-interior-design',         category: 'design',      icon: '🏠', name: 'Diploma in Interior Design',                                      duration: '1 Year',    fees: null, shortDesc: 'Interior design diploma.' },
  { id: 'cert-basic-interior-design',  category: 'design',      icon: '🏠', name: 'Certificate in Basic Interior Design',                            duration: '9 Months',  fees: null, shortDesc: 'Basic interior design certificate.' },
  { id: 'cert-adv-interior-design',    category: 'design',      icon: '🏠', name: 'Certificate in Advanced Interior Design',                         duration: '12 Months', fees: null, shortDesc: 'Advanced interior design certificate.' },
  { id: 'dip-cnc-operating',           category: 'computer',    icon: '🎓', name: 'Diploma in CNC Operating and Programming',                        duration: '1 Year',    fees: null, shortDesc: 'CNC operating and programming diploma.' },
  { id: 'dip-printing-technology',     category: 'computer',    icon: '🎓', name: 'Diploma in Printing Technology',                                  duration: '1 Year',    fees: null, shortDesc: 'Printing technology diploma.' },
  { id: 'cert-robotics',               category: 'computer',    icon: '🤖', name: 'Certificate in Robotics',                                         duration: '3 Months',  fees: null, shortDesc: 'Robotics certificate.' },
  { id: 'cert-solar-technician',       category: 'computer',    icon: '☀️', name: 'Certificate in Solar Technician',                                  duration: '3 Months',  fees: null, shortDesc: 'Solar technician certificate.' },

  // Typing Diplomas
  { id: 'dip-eng-typing-30wpm',        category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based English Typing - 30 W.P.M.',            duration: '6 Months',  fees: null, shortDesc: 'English typing 30 WPM diploma.' },
  { id: 'dip-eng-typing-40wpm',        category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based English Typing - 40 W.P.M.',            duration: '6 Months',  fees: null, shortDesc: 'English typing 40 WPM diploma.' },
  { id: 'dip-eng-typing-60wpm',        category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based English Typing - 60 W.P.M.',            duration: '1 Year',    fees: null, shortDesc: 'English typing 60 WPM diploma.' },
  { id: 'dip-marathi-typing-30wpm',    category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based Marathi Typing - 30 W.P.M.',            duration: '6 Months',  fees: null, shortDesc: 'Marathi typing 30 WPM diploma.' },
  { id: 'dip-marathi-typing-40wpm',    category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based Marathi Typing - 40 W.P.M.',            duration: '6 Months',  fees: null, shortDesc: 'Marathi typing 40 WPM diploma.' },
  { id: 'dip-hindi-typing-30wpm',      category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based Hindi Typing - 30 W.P.M.',              duration: '6 Months',  fees: null, shortDesc: 'Hindi typing 30 WPM diploma.' },
  { id: 'dip-hindi-typing-40wpm',      category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based Hindi Typing - 40 W.P.M.',              duration: '6 Months',  fees: null, shortDesc: 'Hindi typing 40 WPM diploma.' },
  { id: 'dip-stenography',             category: 'typing',      icon: '⌨️', name: 'Diploma in Stenography',                                          duration: '1 Year',    fees: null, shortDesc: 'Stenography diploma.' },
  { id: 'dip-stenography-hindi',       category: 'typing',      icon: '⌨️', name: 'Diploma in Stenography 100 W.P.M. - Hindi',                       duration: '1 Year',    fees: null, shortDesc: 'Hindi stenography 100 WPM diploma.' },
  { id: 'cert-computer-teachers',      category: 'computer',    icon: '👩‍🏫', name: 'Certificate in Computer Teachers Training',                       duration: '6 Months',  fees: null, shortDesc: 'Computer teachers training certificate.' },
  { id: 'dip-comp-teachers-training',  category: 'computer',    icon: '👩‍🏫', name: 'Diploma in Professional Computer Teachers Training',             duration: '1 Year',    fees: null, shortDesc: 'Professional computer teachers training diploma.' },
  { id: 'dip-comp-teachers-edu',       category: 'computer',    icon: '👩‍🏫', name: 'Diploma in Computer Teachers Education',                          duration: '1 Year',    fees: null, shortDesc: 'Computer teachers education diploma.' },
  { id: 'adv-cert-librarian',          category: 'computer',    icon: '📚', name: 'Advance Certificate in Librarian',                                duration: '6 Months',  fees: null, shortDesc: 'Advanced librarian certificate.' },

  // Management & Soft Skills
  { id: 'cert-project-mgmt',           category: 'computer',    icon: '📋', name: 'Certificate in Project Management',                               duration: '3 Months',  fees: null, shortDesc: 'Project management certificate.' },
  { id: 'cert-principles-mgmt',        category: 'computer',    icon: '📋', name: 'Certificate in Principles of Management',                         duration: '3 Months',  fees: null, shortDesc: 'Principles of management certificate.' },
  { id: 'cert-hr-mgmt',                category: 'computer',    icon: '📋', name: 'Certificate in Human Resource Management',                        duration: '3 Months',  fees: null, shortDesc: 'Human resource management certificate.' },
  { id: 'cert-marketing-mgmt',         category: 'computer',    icon: '📋', name: 'Certificate in Marketing Management',                             duration: '3 Months',  fees: null, shortDesc: 'Marketing management certificate.' },
  { id: 'cert-financial-mgmt',         category: 'accounting',  icon: '📋', name: 'Certificate in Financial Management',                             duration: '3 Months',  fees: null, shortDesc: 'Financial management certificate.' },
  { id: 'cert-retail-marketing',       category: 'computer',    icon: '📋', name: 'Certificate in Retail Marketing',                                 duration: '3 Months',  fees: null, shortDesc: 'Retail marketing certificate.' },
  { id: 'cert-front-office',           category: 'computer',    icon: '📋', name: 'Certificate in Front Office Operations Management',               duration: '3 Months',  fees: null, shortDesc: 'Front office operations management.' },
  { id: 'cert-network-mgmt',           category: 'computer',    icon: '📋', name: 'Certificate in Network Management',                               duration: '3 Months',  fees: null, shortDesc: 'Network management certificate.' },
  { id: 'cert-mis',                    category: 'computer',    icon: '📋', name: 'Certificate in Management Information System',                    duration: '1 Month',   fees: null, shortDesc: 'Management information system certificate.' },
  { id: 'cert-entrepreneurship',       category: 'computer',    icon: '📋', name: 'Certificate in Entrepreneurship',                                 duration: '3 Months',  fees: null, shortDesc: 'Entrepreneurship certificate.' },
  { id: 'cert-professional-skill',     category: 'computer',    icon: '📋', name: 'Certificate in Professional Skill Development',                   duration: '3 Months',  fees: null, shortDesc: 'Professional skill development certificate.' },
  { id: 'cert-spoken-english',         category: 'computer',    icon: '🗣️', name: 'Certificate in Spoken English',                                  duration: '3 Months',  fees: null, shortDesc: 'Spoken English certificate.' },
  { id: 'cert-english-grammar',        category: 'computer',    icon: '🗣️', name: 'Certificate in English Grammar',                                  duration: '3 Months',  fees: null, shortDesc: 'English grammar certificate.' },
  { id: 'cert-english-communication',  category: 'computer',    icon: '🗣️', name: 'Certificate in English Communication',                            duration: '6 Months',  fees: null, shortDesc: 'English communication certificate.' },
  { id: 'cert-comm-english',           category: 'computer',    icon: '🗣️', name: 'Certificate in Communication in English',                         duration: '3 Months',  fees: null, shortDesc: 'Communication in English certificate.' },
  { id: 'cert-business-comm',          category: 'computer',    icon: '🗣️', name: 'Certificate in Business Communication',                           duration: '3 Months',  fees: null, shortDesc: 'Business communication certificate.' },
  { id: 'cert-corporate-comm',         category: 'computer',    icon: '🗣️', name: 'Certificate in Corporate Communication',                          duration: '3 Months',  fees: null, shortDesc: 'Corporate communication certificate.' },
  { id: 'dip-retail-mgmt',             category: 'computer',    icon: '🎓', name: 'Diploma in Retail Management',                                    duration: '1 Year',    fees: null, shortDesc: 'Retail management diploma.' },
  { id: 'dip-banking-finance',         category: 'accounting',  icon: '🎓', name: 'Diploma in Banking and Finance Service',                          duration: '6 Months',  fees: null, shortDesc: 'Banking and finance service diploma.' },
  { id: 'cert-insurance',              category: 'computer',    icon: '📋', name: 'Certificate in Principles and Practices of Life and General Insurance', duration: '3 Months', fees: null, shortDesc: 'Life and general insurance certificate.' },
  { id: 'cert-security-mgmt',          category: 'computer',    icon: '🔐', name: 'Certificate in Security Management',                              duration: '3 Months',  fees: null, shortDesc: 'Security management certificate.' },

  // Vocational / Other
  { id: 'cert-fashion-retailing',      category: 'computer',    icon: '👗', name: 'Certificate in Fashion Retailing and Visual Merchandising',       duration: '3 Months',  fees: null, shortDesc: 'Fashion retailing and visual merchandising.' },
  { id: 'cert-basic-beauty-parlour',   category: 'computer',    icon: '💅', name: 'Certificate in Basic Beauty Parlour',                             duration: '3 Months',  fees: null, shortDesc: 'Basic beauty parlour certificate.' },
  { id: 'cert-beauty-parlour',         category: 'computer',    icon: '💅', name: 'Certificate in Beauty Parlour',                                   duration: '6 Months',  fees: null, shortDesc: 'Beauty parlour certificate.' },
  { id: 'dip-beauty-parlour',          category: 'computer',    icon: '💅', name: 'Diploma in Beauty Parlour',                                       duration: '1 Year',    fees: null, shortDesc: 'Beauty parlour diploma.' },
  { id: 'cert-mehandi',                category: 'computer',    icon: '✋', name: 'Certificate in Mehandi Artist',                                   duration: '3 Months',  fees: null, shortDesc: 'Mehandi artist certificate.' },
  { id: 'cert-aari-zardosi',           category: 'computer',    icon: '🧵', name: 'Certificate in Aari and Zardosi Work',                            duration: '2 Months',  fees: null, shortDesc: 'Aari and Zardosi work certificate.' },
  { id: 'cert-basic-tailoring',        category: 'computer',    icon: '🧵', name: 'Certificate in Basic Tailoring',                                  duration: '3 Months',  fees: null, shortDesc: 'Basic tailoring certificate.' },
  { id: 'cert-tailoring',              category: 'computer',    icon: '🧵', name: 'Certificate in Tailoring',                                        duration: '1 Month',   fees: null, shortDesc: 'Tailoring certificate.' },
  { id: 'dip-tailoring',               category: 'computer',    icon: '🧵', name: 'Diploma in Tailoring',                                            duration: '6 Months',  fees: null, shortDesc: 'Tailoring diploma.' },
  { id: 'dip-tailoring-1y',            category: 'computer',    icon: '🧵', name: 'Diploma in Tailoring (1 Year)',                                   duration: '1 Year',    fees: null, shortDesc: 'Tailoring diploma 1 year.' },
  { id: 'cert-basic-fashion',          category: 'computer',    icon: '👗', name: 'Certificate in Basic Fashion Designing',                          duration: '6 Months',  fees: null, shortDesc: 'Basic fashion designing certificate.' },
  { id: 'cert-adv-fashion',            category: 'computer',    icon: '👗', name: 'Certificate in Advanced Fashion Designing',                       duration: '1 Year',    fees: null, shortDesc: 'Advanced fashion designing certificate.' },
  { id: 'dip-fashion-designing',       category: 'computer',    icon: '👗', name: 'Diploma in Fashion Designing',                                    duration: '8 Months',  fees: null, shortDesc: 'Fashion designing diploma.' },
  { id: 'adv-dip-fashion',             category: 'computer',    icon: '👗', name: 'Advance Diploma in Fashion Designing',                            duration: '1 Year',    fees: null, shortDesc: 'Advanced fashion designing diploma.' },
  { id: 'cert-food-nutrition',         category: 'computer',    icon: '🍎', name: 'Certificate in Food and Nutrition',                               duration: '3 Months',  fees: null, shortDesc: 'Food and nutrition certificate.' },
  { id: 'dip-hotel-mgmt',              category: 'computer',    icon: '🏨', name: 'Diploma in Hotel Management',                                     duration: '1 Year',    fees: null, shortDesc: 'Hotel management diploma.' },
  { id: 'dip-food-production',         category: 'computer',    icon: '🍽️', name: 'Diploma in Food Production',                                     duration: '1 Year',    fees: null, shortDesc: 'Food production diploma.' },
  { id: 'dip-yoga',                    category: 'computer',    icon: '🧘', name: 'Diploma in Yoga',                                                 duration: '1 Year',    fees: null, shortDesc: 'Yoga diploma.' },
  { id: 'dip-yoga-6m',                 category: 'computer',    icon: '🧘', name: 'Diploma in Yoga (6 Months)',                                      duration: '6 Months',  fees: null, shortDesc: 'Yoga diploma 6 months.' },
  { id: 'dip-nursery-teacher',         category: 'computer',    icon: '👶', name: 'Diploma in Nursery Teacher Training',                             duration: '1 Year',    fees: null, shortDesc: 'Nursery teacher training diploma.' },
  { id: 'cert-nursery-teacher',        category: 'computer',    icon: '👶', name: 'Certificate in Nursery Teacher Training',                         duration: '4 Months',  fees: null, shortDesc: 'Nursery teacher training certificate.' },
  { id: 'dip-diesel-mechanics',        category: 'computer',    icon: '🔧', name: 'Diploma in Diesel Mechanics',                                     duration: '1 Year',    fees: null, shortDesc: 'Diesel mechanics diploma.' },
  { id: 'dip-welding',                 category: 'computer',    icon: '🔧', name: 'Diploma in Welding Technology',                                   duration: '1 Year',    fees: null, shortDesc: 'Welding technology diploma.' },
  { id: 'dip-electrician',             category: 'computer',    icon: '⚡', name: 'Diploma in Electrician',                                          duration: '1 Year',    fees: null, shortDesc: 'Electrician diploma.' },
  { id: 'cert-electrician',            category: 'computer',    icon: '⚡', name: 'Certificate in Electrician',                                      duration: '1 Month',   fees: null, shortDesc: 'Electrician certificate.' },
  { id: 'cert-wireman',                category: 'computer',    icon: '⚡', name: 'Certificate in Wireman',                                          duration: '6 Months',  fees: null, shortDesc: 'Wireman certificate.' },
  { id: 'cert-plumber',                category: 'computer',    icon: '🔧', name: 'Certificate in Plumber',                                          duration: '1 Month',   fees: null, shortDesc: 'Plumber certificate.' },
  { id: 'dip-plumbing',                category: 'computer',    icon: '🔧', name: 'Diploma in Plumbing',                                             duration: '1 Year',    fees: null, shortDesc: 'Plumbing diploma.' },
  { id: 'cert-carpenter',              category: 'computer',    icon: '🪚', name: 'Certificate in Carpenter',                                        duration: '2 Months',  fees: null, shortDesc: 'Carpenter certificate.' },
  { id: 'dip-carpenter',               category: 'computer',    icon: '🪚', name: 'Diploma in Carpenter',                                            duration: '1 Year',    fees: null, shortDesc: 'Carpenter diploma.' },
  { id: 'cert-mobile-phone-repairing', category: 'computer',    icon: '📱', name: 'Certificate in Mobile Phone Repairing',                           duration: '3 Months',  fees: null, shortDesc: 'Mobile phone repairing certificate.' },
  { id: 'cert-laptop-repairing',       category: 'computer',    icon: '💻', name: 'Certificate in Laptop Repairing',                                 duration: '4 Months',  fees: null, shortDesc: 'Laptop repairing certificate.' },
  { id: 'cert-ac-refrigeration',       category: 'computer',    icon: '❄️', name: 'Certificate in AC and Refrigeration Services',                    duration: '6 Months',  fees: null, shortDesc: 'AC and refrigeration services certificate.' },
  { id: 'dip-ac-refrigeration',        category: 'computer',    icon: '❄️', name: 'Diploma in AC and Refrigeration Services',                        duration: '1 Year',    fees: null, shortDesc: 'AC and refrigeration services diploma.' },
  { id: 'cert-vehicle-repairing',      category: 'computer',    icon: '🚗', name: 'Certificate in Vehicle Repairing',                               duration: '1 Month',   fees: null, shortDesc: 'Vehicle repairing certificate.' },
  { id: 'dip-automobile-engineering',  category: 'computer',    icon: '🚗', name: 'Diploma in Automobile Engineering Services',                      duration: '1 Year',    fees: null, shortDesc: 'Automobile engineering services diploma.' },
  { id: 'cert-fire-safety',            category: 'computer',    icon: '🔥', name: 'Certificate in Industrial Fire and Safety',                       duration: '6 Months',  fees: null, shortDesc: 'Industrial fire and safety certificate.' },
  { id: 'dip-fire-safety',             category: 'computer',    icon: '🔥', name: 'Diploma in Fire and Safety Engineering',                          duration: '1 Year',    fees: null, shortDesc: 'Fire and safety engineering diploma.' },
  { id: 'dip-quantum-health',          category: 'computer',    icon: '🏥', name: 'Diploma in Quantum Magnetic Health Analyzer and Wellness Advisor', duration: '6 Months', fees: null, shortDesc: 'Quantum magnetic health analyzer diploma.' },
  { id: 'adv-dip-adv-it-1y',          category: 'computer',    icon: '🎓', name: 'Advance Diploma in Information Technology (1 Year v2)',            duration: '1 Year',    fees: null, shortDesc: 'Advanced IT diploma.' },
  { id: 'master-dip-comp-acct',        category: 'accounting',  icon: '🎓', name: 'Master Diploma in Computer Applications and Accounting',          duration: '1 Year',    fees: null, shortDesc: 'Master diploma in computer and accounting.' },
  { id: 'adv-cert-adv-excel',          category: 'accounting',  icon: '📊', name: 'Advance Certificate in Advanced Excel',                           duration: '3 Months',  fees: null, shortDesc: 'Advanced Excel certificate.' },
  { id: 'dip-stenography-general',     category: 'typing',      icon: '⌨️', name: 'Diploma in Stenography General',                                  duration: '1 Year',    fees: null, shortDesc: 'Stenography general diploma.' },
  { id: 'cert-adv-wireless',           category: 'computer',    icon: '📡', name: 'Certificate in Advance Wireless and Mobile Communication',        duration: '3 Months',  fees: null, shortDesc: 'Advanced wireless and mobile communication.' },
  { id: 'cert-adv-communication',      category: 'computer',    icon: '📡', name: 'Certificate in Advance Communication',                            duration: '3 Months',  fees: null, shortDesc: 'Advanced communication certificate.' },
  { id: 'cert-wireless-networks',      category: 'computer',    icon: '📡', name: 'Certificate in Wireless Networks: Fundamental and Future Revolutions', duration: '3 Months', fees: null, shortDesc: 'Wireless networks certificate.' },
  { id: 'dip-comp-eng-typing-30-1y',   category: 'typing',      icon: '⌨️', name: 'Diploma in Computer Based English Typing - 30 W.P.M. (1 Year)',   duration: '1 Year',    fees: null, shortDesc: 'English typing 30 WPM diploma 1 year.' },
];

// ── Reviews (add real reviews from verified students) ───────
// DO NOT use fake testimonials. Add only verified reviews.
export const REVIEWS = [
  {
    id: 1,
    name: 'Pranali Tejram Sonkusare',
    course: 'MS-CIT',
    rating: 5,
    review: 'Master Computer Academy मध्ये MS-CIT शिकणे खूपच सोपे आणि आनंददायी वाटले. Sir खूप patience ने समजावून सांगतात. Practical classes मुळे confidence खूप वाढला. मी माझ्या सर्व मैत्रिणींना इथेच शिकण्याचा सल्ला देते!',
    photo: '/images/reviews/pranali-sonkusare.jpeg',
  },
  {
    id: 2,
    name: 'Mayur Ramchandra Dhawale',
    course: 'MS-CIT',
    rating: 5,
    review: 'खूप छान academy आहे. इथे शिकवण्याची पद्धत खूप practical आणि clear आहे. MS-CIT exam मध्ये मला खूप चांगले marks मिळाले. Academy च्या सर्व faculties चे खूप आभार!',
    photo: '/images/reviews/mayur-dhawale.jpeg',
  },
  {
    id: 3,
    name: 'Snehal Ravindra Dhole',
    course: 'MS-CIT',
    rating: 5,
    review: 'Master Computer Academy मध्ये शिकताना खूप मजा आली. प्रत्येक topic step-by-step शिकवला जातो. Doubt असेल तेव्हा Sir नेहमी मदत करतात. हे centre Wathoda मधील सर्वोत्तम computer classes आहे.',
    photo: '/images/reviews/snehal-dhole.jpeg',
  },
  {
    id: 4,
    name: 'Mandar Gajbhiye',
    course: 'MS-CIT',
    rating: 5,
    review: 'येथील शिक्षण पद्धत अत्यंत प्रभावी आहे. Computer चे basic ते advance सर्व काही शिकवले. MS-CIT certificate मिळाल्यावर नोकरीसाठी खूप उपयोग झाला. Master Computer Academy ला माझ्याकडून 5 stars!',
    photo: '/images/reviews/mandar-gajbhiye.jpeg',
  },
];

// ── Gallery images ─────────────────────────────────────────
export const GALLERY_ITEMS = [
  // ── Students in lab ──────────────────────────────────────
  {
    id: 1,
    category: 'students',
    alt: 'Students learning on computers – Master Computer Academy',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.27 (1).jpeg',
  },
  {
    id: 2,
    category: 'students',
    alt: 'Practical computer session – students at Master Computer Academy',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.29.jpeg',
  },

  // ── Classroom / Lab interiors ─────────────────────────────
  {
    id: 3,
    category: 'classroom',
    alt: 'Computer lab interior – Master Computer Academy Wathoda',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.28.jpeg',
  },

  // ── Academy exterior / building ───────────────────────────
  {
    id: 4,
    category: 'classroom',
    alt: 'Master Computer Academy building signboard – Wathoda Layout, Nagpur',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.27.jpeg',
  },
  {
    id: 5,
    category: 'classroom',
    alt: 'Academy entrance with MS-CIT course posters',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.48.jpeg',
  },
  {
    id: 6,
    category: 'classroom',
    alt: 'Academy entrance corridor with DTP sign and MS-CIT banners',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.35.jpeg',
  },
  {
    id: 7,
    category: 'classroom',
    alt: 'MS-CIT entrance door stickers – Master Computer Academy',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.33.jpeg',
  },
  {
    id: 8,
    category: 'classroom',
    alt: 'Academy side view with MS-CIT vertical banner',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.33 (2).jpeg',
  },
  {
    id: 9,
    category: 'classroom',
    alt: 'Exterior corridor – DTP centre and MS-CIT posters',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.33 (1).jpeg',
  },

  // ── Academy activities / highlights ───────────────────────
  {
    id: 10,
    category: 'activity',
    alt: 'MS-CIT and KLiC Diploma course poster – Master Computer Academy',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.34.jpeg',
  },
  {
    id: 11,
    category: 'activity',
    alt: 'Academy office with Best Teacher Award certificates on display',
    src: '/images/WhatsApp Image 2026-09-19 at 19.55.35 (1).jpeg',
  },
];
